# Generated by Django 6.0.3 on 2026-03-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeTableOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('last_confirmed_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='occupied', max_length=50)),
            ],
            options={
                'db_table': 'cafe_table_occupation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id_command', models.AutoField(primary_key=True, serialize=False)),
                ('name_command', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cafe_table_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'command',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyGameSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('daily_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='waiting', max_length=50)),
                ('game_status', models.CharField(default='active', max_length=50)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'daily_game_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GamingTable',
            fields=[
                ('id_gamet', models.AutoField(primary_key=True, serialize=False)),
                ('gamet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gamet_number', models.IntegerField(blank=True, null=True)),
                ('gamet_club', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gaming_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'menu_item',
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'waiter',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True},
        ),
    ]
