# Generated by Django 6.0.3 on 2026-03-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cafetableoccupation_command_dailygamesession_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='client',
            name='email_cl',
            field=models.CharField(blank=True, db_column='email_cl', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='full_name_cl',
            field=models.CharField(blank=True, db_column='full_name_cl', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='image_path',
            field=models.TextField(blank=True, db_column='image_path', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_cl',
            field=models.CharField(blank=True, db_column='phone_cl', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='device_id',
            field=models.CharField(blank=True, db_column='device_id', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(db_column='id_client', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='password_hash',
            field=models.TextField(blank=True, db_column='password_hash', null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='menuitem',
            table='menu',
        ),
    ]
