# Generated by Django 6.0.3 on 2026-03-15 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_menuitem_options_remove_client_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='current_load',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waiter',
            name='role',
            field=models.CharField(default='waiter', max_length=50),
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('record_type', models.CharField(default='revenue', max_length=50)),
                ('payment_method', models.CharField(default='cash', max_length=50)),
                ('status', models.CharField(default='cleared', max_length=50)),
                ('comptable_note', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('command', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit', to='api.command')),
            ],
            options={
                'db_table': 'financial_record',
            },
        ),
    ]
