# Generated by Django 6.0.3 on 2026-03-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_waiter_current_load_waiter_role_financialrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafetableoccupation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='command',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dailygamesession',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gamingtable',
            options={'managed': True},
        ),
    ]
