# Generated by Django 6.0.3 on 2026-03-15 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cafetableoccupation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafetableoccupation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.client'),
        ),
        migrations.AddField(
            model_name='command',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.client'),
        ),
        migrations.AddField(
            model_name='command',
            name='game_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.gamingtable'),
        ),
        migrations.AddField(
            model_name='command',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='api.waiter'),
        ),
        migrations.AddField(
            model_name='dailygamesession',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.client'),
        ),
        migrations.AddField(
            model_name='dailygamesession',
            name='game_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.gamingtable'),
        ),
    ]
