# Generated by Django 6.0.3 on 2026-03-18 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_admin_gametype_rename_menuitem_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrecord',
            name='command',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('name_order', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cafe_table_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.client')),
                ('game_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.gamingtable')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.waiter')),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit', to='api.order'),
        ),
        migrations.DeleteModel(
            name='Command',
        ),
    ]
