# Generated by Django 6.0.3 on 2026-05-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_financialrecord_command_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_session_hours', models.FloatField(default=6.0)),
                ('screen_session_hours', models.FloatField(default=12.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'session_config',
                'managed': True,
            },
        ),
    ]
