# Generated by Django 6.0.5 on 2026-05-26 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sessionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_column='last_seen_at', null=True),
        ),
        migrations.AddField(
            model_name='dailygamesession',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_sessions', to='api.client'),
        ),
        migrations.AddField(
            model_name='dailygamesession',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_sessions', to='api.client'),
        ),
        migrations.CreateModel(
            name='PlayRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gamingtable')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='api.client')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='api.client')),
            ],
            options={
                'db_table': 'play_request',
            },
        ),
    ]
