# Generated by Django 6.0.3 on 2026-05-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_client_last_seen_at_dailygamesession_opponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionconfig',
            name='user_session_hours',
            field=models.FloatField(default=24.0),
        ),
    ]
