# Generated by Django 6.0.3 on 2026-06-04 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_user_session_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='device_id',
        ),
    ]
