from django.urls import path
from . import views

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', views.login, name='login'),
    path('game-status', views.get_game_status, name='game_status'),
    path('join-game', views.join_game, name='join_game'),
    path('place-order', views.place_order, name='place_order'),
    path('cancel-session', views.cancel_session, name='cancel_session'),
    path('confirm-play', views.confirm_play, name='confirm_play'),
    path('user-orders', views.get_user_orders, name='user_orders'),
    path('user-game-history', views.get_user_game_history, name='user_game_history'),
    path('cancel-order', views.cancel_order, name='cancel_order'),
    path('cafe-tables', views.get_cafe_tables, name='cafe_tables'),
    path('occupy-cafe-table', views.occupy_cafe_table, name='occupy_cafe_table'),
    path('confirm-occupation', views.confirm_cafe_table, name='confirm_occupation'),
    path('get-profile', views.get_profile, name='get_profile'),
    path('update-profile', views.update_profile, name='update_profile'),
    path('guest-login', views.guest_login, name='guest_login'),
    # Challenge Matchmaking
    path('connected-players', views.get_connected_players, name='connected_players'),
    path('send-play-request', views.send_play_request, name='send_play_request'),
    path('poll-play-requests', views.poll_play_requests, name='poll_play_requests'),
    path('respond-play-request', views.respond_play_request, name='respond_play_request'),
    path('set-session-winner', views.set_session_winner, name='set_session_winner'),
    # Admin Panel Endpoints (using sys-admin to avoid conflict with django admin)
    path('sys-admin/login', views.admin_login, name='admin_login'),
    path('sys-admin/menu', views.manage_menu, name='manage_menu'),
    path('sys-admin/menu/<int:pk>', views.menu_detail, name='menu_detail'),
    path('sys-admin/waiters', views.manage_waiters, name='manage_waiters'),
    path('sys-admin/waiters/<int:pk>', views.waiter_detail, name='waiter_detail'),
    path('sys-admin/orders', views.get_all_orders, name='all_orders'),
    path('sys-admin/orders/<int:pk>', views.order_detail, name='order_detail'),
    path('sys-admin/orders/<int:pk>/status', views.update_order_status, name='update_order_status'),
    path('sys-admin/clients', views.manage_clients, name='manage_clients'),
    path('sys-admin/clients/<int:pk>', views.client_detail, name='client_detail'),
    path('sys-admin/sessions', views.manage_sessions, name='manage_sessions'),
    path('sys-admin/sessions/<int:pk>', views.session_detail, name='session_detail'),
    path('sys-admin/financials', views.manage_financials, name='manage_financials'),
    path('sys-admin/financials/<int:pk>', views.financial_detail, name='financial_detail'),
    path('sys-admin/history', views.get_master_history, name='master_history'),
    path('sys-admin/game-types', views.manage_game_types, name='manage_game_types'),
    path('sys-admin/game-types/<int:pk>', views.game_type_detail, name='game_type_detail'),
    path('sys-admin/gaming-tables', views.manage_gaming_tables, name='manage_gaming_tables'),
    path('sys-admin/gaming-tables/<int:pk>', views.gaming_table_detail, name='gaming_table_detail'),
    path('sys-admin/admins', views.manage_admins, name='manage_admins'),
    path('sys-admin/admins/<int:pk>', views.admin_detail, name='admin_detail'),
    path('sys-admin/session-config', views.manage_session_config, name='session_config'),
    path('validate-session', views.validate_session, name='validate_session'),
]
